//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandScape
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LandScape()
        {
            this.Photo = new HashSet<Photo>();
        }

        public LandScape(string landScapeName, string landScapeDescription)
        {
            LandScapeName = landScapeName;
            LandScapeDescription = landScapeDescription;
        }

        public int Id { get; set; }
        public string LandScapeName { get; set; }
        public string LandScapeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo { get; set; }
    }
}
